name: Corretor da seção de listas da lista de exercícios da Python Brasil

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configuração de Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Correção do Exercício 01 da seção de Listas
        if: always()
        run: |
          python -m doctest -f secao_04_exercicios_lista/ex_01_vetor_5_numeros.py
      - name: Correção do Exercício 24 da seção de Listas
        if: always()
        run: |
          python -m doctest -f secao_04_exercicios_lista/ex_24_lancamento_de_dados.py
